---
title: "Untitled"
format: html
editor: visual
---

```{r}
library(dplyr)
library(here)
library(tidyverse)

bird_observations <- read_csv(here::here("data", "52_pp52_birds_1.csv"))

sites <- read_csv(here::here("data", "52_pp52_sites_1.csv"))

surveys <- read_csv(here::here("data", "52_pp52_surveys_1.csv"))

taxalist <- read_csv(here::here("data", "52_pp52_taxalist_1.csv"))
```


```{r}
#subsetting by species and site id
birds_subset <- bird_observations |> 
  filter(species_id %in% c("BHCO", "RWBL")) |>
  filter(site_id %in% c("LI-W", "NU-C"))
```

```{r}
#left join practice
birds_left <- birds_subset |> left_join(sites, by = "site_id") |>
  left_join(taxalist, "species_id")

birds_full <- birds_subset |> full_join(sites, by = "site_id")
```

```{r}
bird <- bird_observations |> rename(bird_obs_notes = notes) |> 
  full_join(surveys) |>
  full_join(sites) |>
  full_join(taxalist)|> 
  select(survey_date, common_name, park_name, bird_count) |> 
  mutate(survey_month = lubridate::month(survey_date))|>
  mutate(survey_month = as.factor(survey_month)) |>
  dplyr::relocate(.after = survey_date) |>
  group_by(park_name, survey_month) |>
  summarise(observations = n())|>
  filter(park_name %in% c("Lindo", "Orme", "Palomino", "Sonrisa"))
```
